### ISSUE TITLE
Update dev dependencies

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/a11y-react-emoji#18]
Resolve the following: 
![image](https://user-images.githubusercontent.com/6360367/95576339-49d57080-09fe-11eb-9533-e0fa388992d4.png)

**Comment by arturparkhisenko** [comment]
@SeanMcP do you want still to support both package managers? (NPM and Yarn). It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, we can remove `package-lock.json` and stay with Yarn v1 or do the same but with `yarn.lock` and keep NPM.

**Comment by SeanMcP** [comment]
@arturparkhisenko I would prefer to use `npm` and `package-lock.json` but could be convinced otherwise.
